baseURL: http://example.org/
languageCode: en-us
title: alice
theme: hugo-PaperMod

languages:
    en:
      menu:
        main:
        - name: Project
          pageRef: project
          weight: 2
    